version: '3.3'

services:
  app:
    image: andrepinheiro/nodedockerapp:1.0
    container_name: nodedockerapp
    volumes:
      - .:/app
    build: .
    ports:
      - 4000:4000
    environment:
      - NODE_ENV=dev
    networks:
      - nodejwtnet
    restart: always
networks:
  nodejwtnet:
    driver: bridge
